### ISSUE TITLE
What's the chance of collision?

### ISSUE THREAD

**Issue by sshadmand** [darkskyapp/string-hash#10]
Thanks for creating this. I was curious, what is the chance of two hashes colliding within this algorithm. I was thinking of using it to hash emails.

**Comment by ironwallaby** [comment]
The hashing function operates on unsigned integers. Assuming hashing is uniform, this means the probability of any string being assigned to a particular hash value is 1/4294967296. This is just the [Birthday Problem](https://en.wikipedia.org/wiki/Birthday_problem) with 4294967296 buckets (rather than 365 buckets). Long-story short, the chance of having any collisions reaches 50% after 77,000 or so items.

In practice, hashing isn't uniform since this hashing function is based on a linear recurrence. It does pretty well but you can expect it to be worse for most inputs.

If you're in Node and you're working with large amounts of data, you might be better served by using one of the fast cryptographic hashes, like MD5.
