### ISSUE TITLE
Is there any chance that two strings have same hash?

### ISSUE THREAD

**Issue by chuyik** [darkskyapp/string-hash#6]

**Comment by ironwallaby** [comment]
Yes, and this is a property of all hash functions. Note that there are only 2^32 hash values and far more than 2^32 strings! This guarantees a collision via [the pigeonhole principle](https://en.wikipedia.org/wiki/Pigeonhole_principle).

In fact, this means that there must be a collision even among printable ASCII strings of length 5, because there are 95 printable ASCII characters, and `pow(95,5)>pow(2,32)`. (For Unicode, there are some collisions even between strings of length 2!)

Such collisions, while theoretically possible, shouldn't be all that common in practice. However, you must _always_ plan for the case where collisions occur.
